[runtime]
env = "dev"

[database]
dsn = "host=43.156.247.144 user=new_admin password=Shabitengxun1! dbname=novel port=5432 sslmode=disable TimeZone=UTC"
max_idle_conns = 5
max_open_conns = 10

[redis]
addr = "localhost:6379"
password = ""
db = 0
pool_size = 10
pool_timeout = 10
pool_max_retries = 3
